sudo: false
language: node_js
node_js: '14'
install:
  - travis_wait npm ci
cache:
  directories:
    - '$HOME/.npm'
git:
  depth: 9999
notifications:
  email: false
before_install: dpkg --compare-versions `npm -v` ge 6.11.3 || npm i -g npm@^6.11.3
script:
  - |
    if [[ $SKIP_TESTS != 'true' ]]; then
      npm prune
      npm run checkdeps
      npm run lint
      npm test
    fi
after_success:
  - |
    if [[ $TRAVIS_SECURE_ENV_VARS == 'true' ]]; then
      git remote set-url origin https://cerebraljs:${REPO_COOKER_GITHUB_TOKEN}@github.com/cerebral/overmind;
      git config --global user.email "cerebraljs@gmail.com";
      git config --global user.name "Cerebral JS";
    fi
    if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH == 'next' ]] && [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
      printf "//registry.npmjs.org/:_authToken=$NPM_TOKEN\n" > ~/.npmrc
      npm run release -- --no-parallel --print-release
    fi
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
